New knife
louis-bompart/8IAR125-03 pull request #8
Opened 2016-11-18 20:59 UTC by Heraktone

2016-11-18 23:04 UTC, louis-bompart requested changes

2016-11-18 23:04 UTC, louis-bompart commented on 8IAR125-03/Raven_ObjectEnumerations.h
> +  type_knife,
Met le en dernier et set ca valeur a 14 vu que ca lit dans la map

2016-11-19 14:24 UTC, Heraktone commented on 8IAR125-03/Raven_ObjectEnumerations.h
> +  type_knife,
C'est rajouté mais dans la map j'attendrais peut être qu'on rajotue des spawns avant de rajouter le knife

2016-11-19 17:22 UTC, Guixter reviewed
Mais du coup, le couteau c'est un gun ? x)

2016-11-21 19:13 UTC, Guixter approved these changes

2016-11-22 13:50 UTC, louis-bompart approved these changes

2016-11-23 13:19 UTC, paulbaudy approved these changes

2016-11-23 13:19 UTC, ecocq requested changes
👍

2016-11-23 13:20 UTC, ecocq approved these changes

2016-11-23 13:20 UTC, ecocq approved these changes
💯

2016-11-23 13:20 UTC, merged